import { RouterOSConfigParams } from '../types/mikrotik';

export function generateRouterOSv7Script(params: RouterOSConfigParams): string {
  const lines: string[] = [];

  lines.push(`# ======================================================`);
  lines.push(`# MIKROTIK ROUTEROS v7 CONFIGURATION SCRIPT`);
  lines.push(`# Generated by MikroTik Deployment Tool`);
  lines.push(`# System Identity: ${params.identity}`);
  lines.push(`# ======================================================`);
  lines.push(``);

  // 1. Identity
  lines.push(`# --- 1. SYSTEM IDENTITY ---`);
  lines.push(`/system identity set name="${params.identity}"`);
  lines.push(``);

  // 2. DNS
  const dnsServers = params.dnsServers || '8.8.8.8,1.1.1.1';
  lines.push(`# --- 2. DNS SETTINGS ---`);
  lines.push(`/ip dns set allow-remote-requests=yes servers="${dnsServers}"`);
  lines.push(``);

  // 3. Bridge LAN (ether3, ether4, ether5)
  lines.push(`# --- 3. BRIDGE LAN CONFIGURATION ---`);
  if (params.lanInterface.startsWith('bridge')) {
    lines.push(`/interface bridge add name="${params.lanInterface}" comment="LAN" auto-mac=yes`);
    lines.push(`/interface bridge port add bridge="${params.lanInterface}" interface=ether3 comment="LAN"`);
    lines.push(`/interface bridge port add bridge="${params.lanInterface}" interface=ether4 comment="LAN"`);
    lines.push(`/interface bridge port add bridge="${params.lanInterface}" interface=ether5 comment="LAN"`);
  } else {
    lines.push(`# LAN Interface configured directly on ${params.lanInterface}`);
  }
  lines.push(``);

  // 4. LAN IP Address & DHCP Server
  lines.push(`# --- 4a. LAN IP ADDRESS ---`);
  lines.push(`/ip address add address=${params.lanIpAddress} interface=${params.lanInterface} comment="LAN"`);
  lines.push(``);

  // Helper parsing LAN subnet info
  const parseLanIp = (lanIp: string) => {
    const rawIp = lanIp.split('/')[0].trim();
    const parts = rawIp.split('.');
    if (parts.length === 4) {
      const prefix = `${parts[0]}.${parts[1]}.${parts[2]}`;
      const cidr = lanIp.includes('/') ? lanIp.split('/')[1] : '24';
      return {
        rawIp,
        prefix,
        network: `${prefix}.0/${cidr}`,
        staticRange: `${prefix}.2-${prefix}.99`,
        dhcpPoolRange: `${prefix}.100-${prefix}.254`
      };
    }
    return {
      rawIp: '192.168.99.1',
      prefix: '192.168.99',
      network: '192.168.99.0/24',
      staticRange: '192.168.99.2-192.168.99.99',
      dhcpPoolRange: '192.168.99.100-192.168.99.254'
    };
  };

  const lanInfo = parseLanIp(params.lanIpAddress);

  lines.push(`# --- 4b. DHCP SERVER & POOL LAN ---`);
  lines.push(`/ip pool add name="pool-lan" ranges=${lanInfo.dhcpPoolRange} comment="LAN"`);
  lines.push(`/ip dhcp-server add name="dhcp-lan" interface=${params.lanInterface} lease-time=12h address-pool=pool-lan disabled=no comment="LAN"`);
  lines.push(`/ip dhcp-server network add address=${lanInfo.network} gateway=${lanInfo.rawIp} dns-server=${dnsServers} comment="LAN"`);
  lines.push(``);

  lines.push(`# --- 4c. QOS TRAFFIC PRIORITY ---`);
  lines.push(`/queue simple add name="QoS-1-Static" target=${lanInfo.staticRange} priority=1/1 comment="LAN"`);
  lines.push(`/queue simple add name="QoS-2-DHCP-Normal" target=${lanInfo.dhcpPoolRange} priority=8/8 comment="LAN"`);
  lines.push(``);

  // Helper formatting for IP/Netmask
  const formatIpWithMask = (ip?: string, netmask?: string): string => {
    if (!ip) return '';
    if (ip.includes('/')) return ip;
    if (!netmask) return `${ip}/24`;
    if (netmask.startsWith('/')) return `${ip}${netmask}`;
    
    const maskMap: Record<string, number> = {
      '255.255.255.255': 32, '255.255.255.254': 31, '255.255.255.252': 30,
      '255.255.255.248': 29, '255.255.255.240': 28, '255.255.255.224': 27,
      '255.255.255.192': 26, '255.255.255.128': 25, '255.255.255.0': 24,
      '255.255.254.0': 23,   '255.255.252.0': 22,   '255.255.248.0': 21,
      '255.255.240.0': 20,   '255.255.224.0': 19,   '255.255.192.0': 18,
      '255.255.128.0': 17,   '255.255.0.0': 16
    };
    const cidr = maskMap[netmask] || 24;
    return `${ip}/${cidr}`;
  };

  const host1 = params.failoverCheckHost1 || '8.8.8.8';
  const host2 = params.failoverCheckHost2 || '1.1.1.1';

  // 5. WAN 1 Configuration
  lines.push(`# --- 5. WAN 1 CONFIGURATION ---`);
  if (params.wan1.mode === 'dhcp') {
    if (params.useRecursiveGateway) {
      const dhcpScript1 = `:if (\\$bound = 1) do={/ip route set [find comment=\\"WAN1\\" dst-address=\\"${host1}/32\\"] gateway=\\$\\"gateway-address\\"}`;
      lines.push(`/ip dhcp-client add interface=${params.wan1.interfaceName} add-default-route=no use-peer-dns=yes comment="WAN1" script="${dhcpScript1}"`);
    } else {
      lines.push(`/ip dhcp-client add interface=${params.wan1.interfaceName} add-default-route=yes default-route-distance=1 use-peer-dns=yes comment="WAN1"`);
    }
  } else {
    const wan1Ip = formatIpWithMask(params.wan1.ipAddress, params.wan1.netmask);
    if (wan1Ip) {
      lines.push(`/ip address add address=${wan1Ip} interface=${params.wan1.interfaceName} comment="WAN1"`);
    }
  }
  lines.push(``);

  // 6. WAN 2 Configuration
  lines.push(`# --- 6. WAN 2 CONFIGURATION ---`);
  if (params.wan2.mode === 'dhcp') {
    if (params.useRecursiveGateway) {
      const dhcpScript2 = `:if (\\$bound = 1) do={/ip route set [find comment=\\"WAN2\\" dst-address=\\"${host2}/32\\"] gateway=\\$\\"gateway-address\\"}`;
      lines.push(`/ip dhcp-client add interface=${params.wan2.interfaceName} add-default-route=no use-peer-dns=no comment="WAN2" script="${dhcpScript2}"`);
    } else {
      lines.push(`/ip dhcp-client add interface=${params.wan2.interfaceName} add-default-route=yes default-route-distance=2 use-peer-dns=no comment="WAN2"`);
    }
  } else {
    const wan2Ip = formatIpWithMask(params.wan2.ipAddress, params.wan2.netmask);
    if (wan2Ip) {
      lines.push(`/ip address add address=${wan2Ip} interface=${params.wan2.interfaceName} comment="WAN2"`);
    }
  }
  lines.push(``);

  // 7. Routing & Auto Failover
  lines.push(`# --- 7. ROUTING & AUTO FAILOVER (RouterOS v7) ---`);

  if (params.useRecursiveGateway) {
    // Mode A: Recursive Gateway Failover (Fast Netwatch Switching)
    lines.push(`# Mode: Recursive Gateway Failover (Internet Host Ping Check)`);
    lines.push(`# Catatan: Untuk mode DHCP Client, gateway awal rute host adalah temporary placeholder.`);
    lines.push(`# Begitu DHCP Client aktif (bound), script DHCP akan otomatis mengupdate gateway rute host ke IP Gateway modem yang didapat.`);
    
    // Gateway for Host 1 (WAN1)
    const gw1 = params.wan1.mode === 'static' ? (params.wan1.gateway || '192.168.1.1') : '192.168.1.1';
    lines.push(`/ip route add dst-address=${host1}/32 gateway=${gw1} scope=10 target-scope=10 comment="WAN1"`);

    // Gateway for Host 2 (WAN2)
    const gw2 = params.wan2.mode === 'static' ? (params.wan2.gateway || '192.168.2.1') : '192.168.2.1';
    lines.push(`/ip route add dst-address=${host2}/32 gateway=${gw2} scope=10 target-scope=10 comment="WAN2"`);

    // Default Routes 0.0.0.0/0 pointing to Recursive Hosts
    lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${host1} distance=1 check-gateway=ping target-scope=11 comment="WAN1"`);
    lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${host2} distance=2 check-gateway=ping target-scope=11 comment="WAN2"`);

    // Netwatch Watchdog for Instant Switching (< 3s)
    lines.push(``);
    lines.push(`# Netwatch Fast Auto-Switching Guard`);
    const netwatchDown1 = `:if ([/ip route get [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance] != 10) do={/log warning \\"WAN1 Internet DOWN! Switching to WAN2\\"; /ip route set [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance=10}`;
    const netwatchUp1 = `:if ([/ip route get [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance] != 1) do={/log info \\"WAN1 Internet RESTORED! Switching back to WAN1\\"; /ip route set [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance=1}`;
    lines.push(`/tool netwatch add host=${host1} interval=3s timeout=2s comment="WAN1" down-script="${netwatchDown1}" up-script="${netwatchUp1}"`);

    const netwatchDown2 = `:if ([/ip route get [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance] != 20) do={/log warning \\"WAN2 Internet DOWN!\\"; /ip route set [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance=20}`;
    const netwatchUp2 = `:if ([/ip route get [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance] != 2) do={/log info \\"WAN2 Internet RESTORED!\\"; /ip route set [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance=2}`;
    lines.push(`/tool netwatch add host=${host2} interval=3s timeout=2s comment="WAN2" down-script="${netwatchDown2}" up-script="${netwatchUp2}"`);
  } else {
    // Mode B: Standard Gateway Failover (Direct Modem Gateway)
    lines.push(`# Mode: Standard Gateway Failover`);

    if (params.wan1.mode === 'static' && params.wan1.gateway) {
      lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${params.wan1.gateway} distance=1 check-gateway=ping comment="WAN1"`);
    }

    if (params.wan2.mode === 'static' && params.wan2.gateway) {
      lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${params.wan2.gateway} distance=2 check-gateway=ping comment="WAN2"`);
    }
  }
  lines.push(``);

  // 8. Firewall NAT (Masquerade for WAN1 & WAN2)
  if (params.enableNat) {
    lines.push(`# --- 8. FIREWALL NAT (MASQUERADE) ---`);
    lines.push(`/ip firewall nat add chain=srcnat action=masquerade out-interface=${params.wan1.interfaceName} comment="WAN1"`);
    lines.push(`/ip firewall nat add chain=srcnat action=masquerade out-interface=${params.wan2.interfaceName} comment="WAN2"`);
    lines.push(``);
  }

  // 9. FastTrack Firewall Rule
  if (params.enableFastTrack) {
    lines.push(`# --- 9. FASTTRACK ACCELERATION ---`);
    lines.push(`/ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related comment="FastTrack"`);
    lines.push(`/ip firewall filter add chain=forward action=accept connection-state=established,related comment="Accept-Established"`);
    lines.push(``);
  }

  // 10. Admin Security & Services
  if (params.adminPassword) {
    lines.push(`# --- 10. ADMIN PASSWORD SECURITY ---`);
    lines.push(`/user set [find name="admin"] password="${params.adminPassword}"`);
    lines.push(``);
  }

  lines.push(`# --- END OF SCRIPT ---`);
  return lines.join('\n');
}

export function generateFailoverOnlyScript(params: RouterOSConfigParams): string {
  const lines: string[] = [];
  const host1 = params.failoverCheckHost1 || '8.8.8.8';
  const host2 = params.failoverCheckHost2 || '1.1.1.1';

  lines.push(`# ======================================================`);
  lines.push(`# MIKROTIK ROUTEROS v7 FAILOVER ONLY SCRIPT`);
  lines.push(`# System Identity: ${params.identity}`);
  lines.push(`# ======================================================`);
  lines.push(``);

  lines.push(`# --- ROUTING & AUTO FAILOVER (RouterOS v7) ---`);
  if (params.useRecursiveGateway) {
    lines.push(`# Mode: Recursive Gateway Failover (Internet Host Ping Check)`);
    if (params.wan1.mode === 'dhcp' || params.wan2.mode === 'dhcp') {
      lines.push(`# Catatan: Untuk mode DHCP Client, gateway rute host awal (192.168.x.x) adalah placeholder temporary.`);
      lines.push(`# Pastikan script di /ip dhcp-client diaktifkan agar otomatis ter-update saat DHCP lease aktif.`);
    }

    const gw1 = params.wan1.mode === 'static' ? (params.wan1.gateway || '192.168.1.1') : '192.168.1.1';
    lines.push(`/ip route add dst-address=${host1}/32 gateway=${gw1} scope=10 target-scope=10 comment="WAN1"`);

    const gw2 = params.wan2.mode === 'static' ? (params.wan2.gateway || '192.168.2.1') : '192.168.2.1';
    lines.push(`/ip route add dst-address=${host2}/32 gateway=${gw2} scope=10 target-scope=10 comment="WAN2"`);

    lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${host1} distance=1 check-gateway=ping target-scope=11 comment="WAN1"`);
    lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${host2} distance=2 check-gateway=ping target-scope=11 comment="WAN2"`);

    lines.push(``);
    lines.push(`# Netwatch Fast Auto-Switching Guard`);
    const netwatchDown1 = `:if ([/ip route get [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance] != 10) do={/log warning \\"WAN1 Internet DOWN! Switching to WAN2\\"; /ip route set [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance=10}`;
    const netwatchUp1 = `:if ([/ip route get [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance] != 1) do={/log info \\"WAN1 Internet RESTORED! Switching back to WAN1\\"; /ip route set [find comment=\\"WAN1\\" dst-address=\\"0.0.0.0/0\\"] distance=1}`;
    lines.push(`/tool netwatch add host=${host1} interval=3s timeout=2s comment="WAN1" down-script="${netwatchDown1}" up-script="${netwatchUp1}"`);

    const netwatchDown2 = `:if ([/ip route get [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance] != 20) do={/log warning \\"WAN2 Internet DOWN!\\"; /ip route set [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance=20}`;
    const netwatchUp2 = `:if ([/ip route get [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance] != 2) do={/log info \\"WAN2 Internet RESTORED!\\"; /ip route set [find comment=\\"WAN2\\" dst-address=\\"0.0.0.0/0\\"] distance=2}`;
    lines.push(`/tool netwatch add host=${host2} interval=3s timeout=2s comment="WAN2" down-script="${netwatchDown2}" up-script="${netwatchUp2}"`);
  } else {
    if (params.wan1.mode === 'static' && params.wan1.gateway) {
      lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${params.wan1.gateway} distance=1 check-gateway=ping comment="WAN1"`);
    }
    if (params.wan2.mode === 'static' && params.wan2.gateway) {
      lines.push(`/ip route add dst-address=0.0.0.0/0 gateway=${params.wan2.gateway} distance=2 check-gateway=ping comment="WAN2"`);
    }
  }

  lines.push(``);
  lines.push(`# --- END OF FAILOVER SCRIPT ---`);
  return lines.join('\n');
}
